# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.10.13'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    pip install selenium==4.15.2
    pip install Appium-Python-Client==3.1.0
  displayName: 'Install Selenium and Appium'

- script: |
    curl https://saucelabs.com/downloads/sc-4.9.2-linux.tar.gz | tar -xz
    chmod 777 -R ./sc-4.9.2-linux
    PATH=./sc-4.9.2-linux/bin:$PATH
    sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY  --region eu-central -i "rdc-on-sauce-tunnel-eu" -v -s &
  displayName: 'Download and Install Sauce Connect'

- script: |
    python3 ./testcases/myTest.py
  displayName: 'Run Tests on SauceLabs'
